spring.datasource.url=jdbc:postgresql://dpg-d72ng4u3jp1c73ejn2ng-a:5432/carhub_67er
spring.datasource.username=carhub_67er_user
spring.datasource.password=fIeq5DoJyd6FFMc7CcrncfgYVs8JNJzZ

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=rudruvenkatesh9@gmail.com
spring.mail.password=okzwmgwnrzjawnxw
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
server.port=${PORT:8080}
carhub.admin.email=rudruvenkatesh9@gmail.com
